---
# Configuration taken and modified from https://github.com/maxmind/MaxMind-DB-Reader-dotnet/blob/master/.travis.yml
sudo: false
language: csharp
# dotnet cli requires Ubuntu 14.04
sudo: required
dist: trusty

# dotnet cli requires OSX 10.10
osx_image: xcode7.1

addons:
  apt:
    packages:
    - libunwind8

os:
  - osx
  - linux

env:
  matrix:
    - CLI_VERSION: Latest
      Configuration: Debug
      Framework: netcoreapp1.0
    - CLI_VERSION: Latest
      Configuration: Release
      Framework: netcoreapp1.0

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl && brew link --force openssl ; fi
  # Download script to install dotnet cli
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 1.0.0-preview2-003121 --install-dir ~/dotnet

  - export DOTNET_INSTALL_DIR="~/dotnet"

  # Add dotnet to PATH
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

install:
  - git submodule update --init --recursive
  - which dotnet;
    if [ $? -eq 0 ]; then
      echo "Using dotnet:";
      dotnet --info;
    else
      echo "dotnet.exe not found"
      exit 1;
    fi

  # Restore dependencies
  - dotnet restore

  - FrameworkLibsMoniker="netstandard1.1

  # Build projects 
  - dotnet build -c $Configuration -f $FrameworkLibsMoniker ./src/SapientGuardian.ConfigureAll

script:
  - cd test/ConfigureAllTests
  - dotnet test
