version: 1.0.0-{build}
image: Visual Studio 2015
build_script:
- cmd: >-
    dotnet restore -v Warning	

    dotnet pack .\src\SapientGuardian.ConfigureAll -o .\artifacts\SapientGuardian.ConfigureAll -c Release
test_script:
- cmd: >-
    cd test\ConfigureAllTests

    dotnet test
artifacts:
- path: 'artifacts\**\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: 7nX5a7V6wWbtPSJ6bQSU9BRZwJEdn70w0Ydlf5fuk44Gjk9BVgxnYK6u8MNzT2yA
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true